version: 2

updates:
  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    groups:
      spring-boot:
        patterns:
          - "org.springframework.boot*"
          - "io.spring.dependency-management*"
      spotbugs:
        patterns:
          - "com.github.spotbugs*"
      shedlock:
        patterns:
          - "net.javacrumbs.shedlock*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
