spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 70229857322-3gbp0d2ap1li9ioroldv9dpi8e8c9slf.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code