spring:
  application:
    name: kraft-book

  # 공통 JPA 옵션(DDL 생성은 프로파일별로)
  jpa:
    properties:
      hibernate:
        format_sql: true         # SQL 포맷팅
        use_sql_comments: true
    open-in-view: false          # OSIV 비활성 (웹 뷰에서 지연 로딩 막기)

  # SQL 스크립트 자동 실행 방지 (스키마 관리는 Flyway가 담당)
  sql:
    init:
      mode: never

  # Thymeleaf 공통
  thymeleaf:
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html
    # 템플릿 캐시는 dev에서만 끄고, 공통은 켜둠 (프로파일에서 override)
    cache: true

  jackson:
    time-zone: Asia/Seoul
    serialization:
      write-dates-as-timestamps: false

  profiles:
    include: oauth
    active: dev                   # 기본 프로파일 (로컬 개발용)
    group:
      dev: dev,h2
      mysql: mysql

server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

logging:
  level:
    # 애플리케이션 로그
    com.kraft.book: INFO
    # Hibernate SQL/바인딩 로그 (프로파일에서 더 자세히 조정)
    org.hibernate.SQL: INFO
    org.hibernate.orm.jdbc.bind: INFO   # 파라미터 바인딩 (Hibernate 6)
