spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/kraft?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8&connectionCollation=utf8mb4_0900_ai_ci&serverTimezone=Asia/Seoul
    username: kraft
    password: kraft1234
  jpa:
    hibernate:
      ddl-auto: validate   # 운영/실DB는 validate 권장
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  sql:
    init:
      mode: always         # 처음 스키마 올릴 때만 on → 이후에는 never 권장
      schema-locations: classpath:schema-mysql.sql
