spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
  session:
    jdbc:
      initialize-schema: never

  messages:
    basename: messages
    encoding: UTF-8
logging:
  level:
    org.springframework: info
