-- clean
DROP TABLE IF EXISTS posts;
DROP TABLE IF EXISTS users;

-- users
CREATE TABLE users (
                       id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       created_date  TIMESTAMP      NOT NULL,
                       modified_date TIMESTAMP      NOT NULL,
                       email         VARCHAR(255)   NOT NULL,
                       name          VARCHAR(255)   NOT NULL,
                       picture       VARCHAR(255),
                       role          VARCHAR(10)    NOT NULL,
                       CONSTRAINT ck_users_role CHECK (role IN ('GUEST','USER')),
                       CONSTRAINT uq_users_email UNIQUE (email)
);

-- posts
CREATE TABLE posts (
                       id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       created_date  TIMESTAMP      NOT NULL,
                       modified_date TIMESTAMP      NOT NULL,
                       author        VARCHAR(255),
                       content       CLOB           NOT NULL,
                       title         VARCHAR(500)   NOT NULL
);

CREATE INDEX idx_posts_author ON posts(author);
