package com.kraft.common.error;

import org.springframework.http.HttpStatus;

/**
 * M-2: {@link ApiException}이 (HttpStatus, 문자열 code) 쌍을 호출부마다 직접 타이핑하던 것을
 * enum으로 승격했다. 84곳의 호출부에서 상태코드-code 오타/불일치를 컴파일 시점에 방지한다.
 */
public enum ApiErrorCode {

    INVALID_BALL(HttpStatus.BAD_REQUEST),
    INVALID_BONUS_NUMBER(HttpStatus.BAD_REQUEST),
    INVALID_NUMBERS(HttpStatus.BAD_REQUEST),
    INVALID_ROUND(HttpStatus.BAD_REQUEST),
    INVALID_LIMIT(HttpStatus.BAD_REQUEST),
    ROUND_NOT_FOUND(HttpStatus.NOT_FOUND),

    DEVICE_TOKEN_REQUIRED(HttpStatus.BAD_REQUEST),
    INVALID_DEVICE_TOKEN(HttpStatus.BAD_REQUEST),
    DEVICE_ALREADY_CLAIMED(HttpStatus.CONFLICT),

    OAUTH_PROVIDER_UNSUPPORTED(HttpStatus.BAD_REQUEST),
    OAUTH_ATTRIBUTE_MISSING(HttpStatus.UNAUTHORIZED),

    SAVED_NUMBER_NOT_FOUND(HttpStatus.NOT_FOUND),
    SAVED_LIMIT_REACHED(HttpStatus.CONFLICT),

    RECOMMENDATION_SET_NOT_FOUND(HttpStatus.NOT_FOUND),
    RECOMMENDATION_SET_NOT_OWNED(HttpStatus.FORBIDDEN),
    RECOMMENDATION_SET_ATTACHED_TO_POST(HttpStatus.CONFLICT),
    // I-04: strategy/explanation_codes 저장값이 현재 enum과 더 이상 맞지 않는 레거시 행을
    // 디코드하려 할 때(예: 리팩터 이전에 생성된 추천 세트) 원시 RuntimeException이 그대로
    // 새어나가 "예상하지 못한 서버 오류가 발생했습니다"라는 정체불명의 500이 되던 문제를 막는다.
    RECOMMENDATION_SET_UNAVAILABLE(HttpStatus.CONFLICT),
    TOO_MANY_LOCKED_NUMBERS(HttpStatus.BAD_REQUEST),
    LOCKED_EXCLUDED_CONFLICT(HttpStatus.BAD_REQUEST),
    INVALID_RECOMMENDATION_STRATEGY(HttpStatus.BAD_REQUEST),
    TOO_MANY_EXCLUSIONS(HttpStatus.BAD_REQUEST),
    INSUFFICIENT_UNIQUE_COMBINATIONS(HttpStatus.BAD_REQUEST),
    RECOMMENDATION_HISTORY_NOT_READY(HttpStatus.SERVICE_UNAVAILABLE),

    COMMUNITY_CATEGORY_INVALID(HttpStatus.BAD_REQUEST),
    COMMUNITY_SEARCH_QUERY_INVALID(HttpStatus.BAD_REQUEST),
    COMMUNITY_SELF_BLOCK_NOT_ALLOWED(HttpStatus.BAD_REQUEST),
    COMMUNITY_BLOCKED_INTERACTION(HttpStatus.FORBIDDEN),
    COMMUNITY_POST_NOT_FOUND(HttpStatus.NOT_FOUND),
    COMMUNITY_POST_NOT_VISIBLE(HttpStatus.NOT_FOUND),
    COMMUNITY_POST_NOT_OWNER(HttpStatus.FORBIDDEN),
    COMMUNITY_POST_VERSION_CONFLICT(HttpStatus.CONFLICT),
    COMMUNITY_COMMENT_NOT_FOUND(HttpStatus.NOT_FOUND),
    COMMUNITY_COMMENT_NOT_OWNER(HttpStatus.FORBIDDEN),
    COMMUNITY_COMMENT_PARENT_NOT_FOUND(HttpStatus.NOT_FOUND),
    COMMUNITY_COMMENT_PARENT_DELETED(HttpStatus.BAD_REQUEST),
    COMMUNITY_COMMENT_PARENT_MISMATCH(HttpStatus.BAD_REQUEST),
    COMMUNITY_COMMENT_REPLY_DEPTH_EXCEEDED(HttpStatus.BAD_REQUEST),
    COMMUNITY_USER_NOT_FOUND(HttpStatus.NOT_FOUND),
    REPORT_ALREADY_EXISTS(HttpStatus.CONFLICT),
    REPORT_TARGET_NOT_FOUND(HttpStatus.NOT_FOUND),

    LOTTO_SOURCE_DISABLED(HttpStatus.SERVICE_UNAVAILABLE),
    LOTTO_SOURCE_CIRCUIT_OPEN(HttpStatus.BAD_GATEWAY),
    LOTTO_SOURCE_EMPTY(HttpStatus.BAD_GATEWAY),
    LOTTO_SOURCE_INVALID_DATE(HttpStatus.BAD_GATEWAY),
    LOTTO_SOURCE_PARSE_ERROR(HttpStatus.BAD_GATEWAY),
    LOTTO_SOURCE_ROUND_MISMATCH(HttpStatus.BAD_GATEWAY),
    LOTTO_SOURCE_ROUND_NOT_FOUND(HttpStatus.BAD_GATEWAY),
    LOTTO_SOURCE_VALIDATION_ERROR(HttpStatus.BAD_GATEWAY),

    INVALID_OPERATION_TYPE(HttpStatus.BAD_REQUEST),
    INVALID_EXECUTION_STATUS(HttpStatus.BAD_REQUEST),
    INVALID_FROM_DATE(HttpStatus.BAD_REQUEST),
    INVALID_TO_DATE(HttpStatus.BAD_REQUEST),
    INTERNAL_ERROR(HttpStatus.INTERNAL_SERVER_ERROR);

    private final HttpStatus status;

    ApiErrorCode(HttpStatus status) {
        this.status = status;
    }

    public HttpStatus status() {
        return status;
    }
}
