ALTER TABLE winning_numbers MODIFY COLUMN created_at DATETIME(6) NOT NULL;
ALTER TABLE winning_numbers MODIFY COLUMN fetched_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6);
ALTER TABLE winning_numbers MODIFY COLUMN updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6);
ALTER TABLE lotto_fetch_logs MODIFY COLUMN fetched_at DATETIME(6) NOT NULL;
