-- Spring Session JDBC의 세션 테이블 스크립트(MariaDB 전용, 멱등 버전).
--
-- spring-session-jdbc가 기본으로 쓰는 schema-mysql.sql은 CREATE TABLE/CREATE INDEX에
-- IF NOT EXISTS가 없다. local 프로파일은 initialize-schema: always라 매 기동마다 이 스크립트를
-- 다시 실행하는데, docker 볼륨에 테이블이 이미 남아 있으면 5줄의 WARN이 찍힌다
-- ("Table 'SPRING_SESSION' already exists", "Duplicate key name 'SPRING_SESSION_IX1~IX3'").
-- 실패해도 무시하고 넘어가므로 동작에는 문제가 없었지만, 매번 나오는 가짜 경고라 실제 문제를
-- 가린다. MariaDB 10.1.4+가 지원하는 IF NOT EXISTS를 붙여 조용히 넘어가게 한다.
--
-- 내용 자체는 spring-session-jdbc 4.1.1의 schema-mysql.sql과 동일하다(버전을 올릴 때
-- 원본이 바뀌었는지 확인할 것).

CREATE TABLE IF NOT EXISTS SPRING_SESSION (
	PRIMARY_ID CHAR(36) NOT NULL,
	SESSION_ID CHAR(36) NOT NULL,
	CREATION_TIME BIGINT NOT NULL,
	LAST_ACCESS_TIME BIGINT NOT NULL,
	MAX_INACTIVE_INTERVAL INT NOT NULL,
	EXPIRY_TIME BIGINT NOT NULL,
	PRINCIPAL_NAME VARCHAR(100),
	CONSTRAINT SPRING_SESSION_PK PRIMARY KEY (PRIMARY_ID)
) ENGINE=InnoDB ROW_FORMAT=DYNAMIC;

CREATE UNIQUE INDEX IF NOT EXISTS SPRING_SESSION_IX1 ON SPRING_SESSION (SESSION_ID);
CREATE INDEX IF NOT EXISTS SPRING_SESSION_IX2 ON SPRING_SESSION (EXPIRY_TIME);
CREATE INDEX IF NOT EXISTS SPRING_SESSION_IX3 ON SPRING_SESSION (PRINCIPAL_NAME);

CREATE TABLE IF NOT EXISTS SPRING_SESSION_ATTRIBUTES (
	SESSION_PRIMARY_ID CHAR(36) NOT NULL,
	ATTRIBUTE_NAME VARCHAR(200) NOT NULL,
	ATTRIBUTE_BYTES BLOB NOT NULL,
	CONSTRAINT SPRING_SESSION_ATTRIBUTES_PK PRIMARY KEY (SESSION_PRIMARY_ID, ATTRIBUTE_NAME),
	CONSTRAINT SPRING_SESSION_ATTRIBUTES_FK FOREIGN KEY (SESSION_PRIMARY_ID) REFERENCES SPRING_SESSION(PRIMARY_ID) ON DELETE CASCADE
) ENGINE=InnoDB ROW_FORMAT=DYNAMIC;
